= What Can Repose Do For You?
:backend: deckjs
:menu:


== What Is Repose?

[%step]
* It's a reverse proxy
* It's an API management tool
* It does all the things that every service needs to do
[%step]
** Request Logging
** Rate Limiting
** Authentication
** Authorization
** Role Based Access Control
** User Access Events


== What Does It Look Like?

[%step]
--

[ditaa, big-picture-diagram, png]
....
                  +=-----------------------------------+
                  | Your Service to the Outside World  |
+------+          |  +------+       +---------------+  |
|      +------------>|      +=----->|     Your      |  |
|Client|          |  |Repose|       |    Actual     |  |
|      |<------------+      |<-----=+    Service    |  |
+------+          |  +------+       +---------------+  |
                  +------------------------------------+
....
--

[%step]
Zoom In and Enhance

[%step]
--

[ditaa, repose-diagram, png]
....
             +------------------------------------------+
             |                  Repose                  |
             | +-----------+                            |
             | | +----+    |                            |
             | | |    |    v                            |
             | | | +--+-------+   /-----------\         |
             | | | | Filter 1 +=->| Service A |         |
------------>|-+ | +----------+   \-----------/     +-->+=------->
             |   | | Filter 2 +=-+                  |   |
             |   | +----------+  |    /-----------\ |   |
<------------+<--+ | Filter n |  +--->| Service B | | +-|<-------=+
             |     +-------+--+       \-----------/ | | |
             |        ^    |                        | | |
             |        |    +------------------------+ | |
             |        +-------------------------------+ |
             +------------------------------------------+
....
--

[%step]
Zoom Out

== What Does It Look Like?

[ditaa, big-picture-diagram, png]
....
                  +=-----------------------------------+
                  | Your Service to the Outside World  |
+------+          |  +------+       +---------------+  |
|      +------------>|      +=----->|     Your      |  |
|Client|          |  |Repose|       |    Actual     |  |
|      |<------------+      |<-----=+    Service    |  |
+------+          |  +------+       +---------------+  |
                  +------------------------------------+
....

[%step]
Zoom In and Enhance

[%step]
--

[ditaa, your-service-diagram, png]
....
             +------------------------------------------+
             |               Your Service               |
             |                                          |
             |                                          |
             |                                          |
             |                                          |
             |  Man, I don't know.                      |
=----------->|  This is your service;                   |
             |  I have no idea what's going on in here. |
             |  It could be anything.                   |
<-----------=+  Even a boat.                            |
             |  Is it a boat?                           |
             |                                          |
             |                                          |
             |                                          |
             +------------------------------------------+
....
--


== Demo Time

[%step]
Are you ready for it?

[%step]
Are you sure? Because this is going to blow your mind.

[%step]
Last chance to leave.

[%step]
Let's do this.


== Passthrough Example

* This configuration is questionably useful.
* All it really does is take requests on one port and send them out on another.
* Let's us know that *Repose* is installed correctly.

[source, bash]
----
$ curl -v -X GET http://localhost:8080
----

tag: `passthrough`


== Http Logging Example

* Records details about the request/response in a separate log.
* No really, that's it.

[source, bash]
----
$ curl -v -X GET http://localhost:8080
----

tag: `http-log`


== Rate Limiting Example

* Sets up header normalization so rate limiting can't be spoofed.
* Sets up the IP user filtered to get IP information for...
* Sets up rate limiting for different resources

[source, bash]
----
$ curl -v -X GET http://localhost:8080/service/foo
$ curl -v -X POST http://localhost:8080/service/foo
$ curl -v -X GET http://localhost:8080
----

tag: `rate-limiting`


== Authentication/Authorization Example

* Authenticates a Keystone v2 user token
* Authorizes against the requested tenant
* Authorizes against the endpoints in their catalog
* Enables role based rate limiting

[source, bash]
----
$ curl -v -X GET http://localhost:8080/service/1234567890/foo
$ curl -v -X GET -H "X-Auth-Token: 1234567890" http://localhost:8080/service/1234567890/foo
----

tag: `keystone`


== Role Based Access Control Example

* Uses the roles and groups from Keystone to grant access to specific resources
* Can restrict by method as well as role

[source, bash]
----
$ curl -v -X GET -H "X-Auth-Token: 1234567890" http://localhost:8080/service/1234567890/foo
$ curl -v -X POST -H "X-Auth-Token: 1234567890" http://localhost:8080/service/1234567890/foo
----

tag: `rbac`


== User Access Events Example

* Collects request and response information for the event
* Event is moustache template based
* Ships with a *Cloud Feeds* ready template
* *Flume* ready with a separately published *Cloud Feeds* based sink

[source, bash]
----
$ curl -v -X GET -H "X-Auth-Token: 1234567890" http://localhost:8080/service/1234567890/foo
$ curl -v -X POST -H "X-Auth-Token: 1234567890" http://localhost:8080/service/1234567890/foo
----

tag: `uae`


== Other Filters

=== Authentication/Authorization
* Keystone v2 Basic Auth
* Keystone v3
* Valkyrie

=== Rate Limiting
* Header User
* URI User

== Other Filters

=== Header Manipulation
* Add Header
* Body Extractor to Header
* Header Translation
* URI Extractor to Header

=== Body Manipulation
* Body Patcher
* Scripting
* Translation

=== URI Manipulation
* URI Normalization
* URI Stripper

== Other Filters

=== Routing
* Destination Router
* Versioning

=== Other Stuff
* API Validator
* CORS


== Questions?

You have them.

[%step]
I might have answers.


== Thanks

=== Contact Us

* Email: reposecore@rackspace.com
* IRC: #repose on freenode
* Internal slack: #repose or @reposeninja

=== More Info

* Site: http://www.openrepose.org
* This Presentation: http://www.github.com/rackerlabs/repose-tech-talk
